#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$SCRIPT_DIR/.."

VER=$(cat VERSION)

echo "About to release version $VER"
read -p "Are you sure you want to continue? " -n 1 -r
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    exit 1
fi

git add -A
git commit -m "release $VER"
git tag -a -m "tagging $VER" "v$VER"
git push --all
git push --tags
