#!/usr/bin/env bash

GREEN='\033[0;32m'
YELLOW='\033[0;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo ""

echo -e "${GREEN}Pre Update Status${NC}"
go mod graph

echo ""

echo -e "${GREEN}UPDATE${NC}"
go mod tidy
go mod download

echo ""

echo -e "${RED}POST Update Status${NC}"
go mod graph

echo ""

echo -e "${YELLOW}You should check git status now${NC}"
