#!/bin/bash

# TODO: if prev flag was -f they are looking for a file

_dmk_args()
{
    COMPREPLY=()
    local cur="${COMP_WORDS[COMP_CWORD]}"
    # local prev="${COMP_WORDS[COMP_CWORD-1]}"

    if [[ ${cur} == -* ]] ; then
        local opts
        opts="-h -c -f -v -listSteps"
        COMPREPLY=( $(compgen -W "${opts}" -- "${cur}") )
        return 0
    else
        local steps
        steps=$(dmk -listSteps | tr '\r\n\t' ' ')
        COMPREPLY=( $(compgen -W "${steps}" -- "${cur}") )
        return 0
    fi
}
complete -F _dmk_args dmk
