name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check Out Code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: "^1.14"

    - name: Go Version
      run: go version

    - name: Get Dependencies
      run: echo "Currently, all deps should be vendored"

    - name: Lint/Vet
      run: make lint

    - name: Test
      run: make testv

